language: node_js

node_js:
  - "6"
  - "8"
  - "10"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

install:
  - npm install

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - npm run build
